In [3]:
import numpy as np
B = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [5]:
B[:2,:3]  # hai dòng ,3 cột

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
B[:3,::2]   # Lấy các hàng bắt đầu từ 0 đến hàng 3(ko bao gồm hàng này)
            #Lấy các cột với bước nhảy là 2 bắt đầu từ cột 0

array([[1, 3],
       [5, 7],
       [9, 1]])

In [7]:
B[ ::-1, ::-1]   # Lấy các hàng từ cuối lên bước nhảy là -1
                # Lấy các hàng từ cột bên phải sang, bước nhảy là -1

array([[2, 1, 0, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])