In [1]:
import numpy as np
# Tạo mảng 2 chiều 3x3
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc
arr_view = arr_2d[:2, :2].view()
print(arr_view)     # in mảng còn arr vừa dc slicing từ hàm view


[[1 2]
 [4 5]]


In [ ]:
# Thay đổi giá trị trong view
arr_view[0,0]= 100 #Chỉnh sửa phần tử ở dòng 0 cột 0 thành 100
print(arr_view)

[[100   2]
 [  4   5]]


In [4]:
print("Mảng gốc sau khi thay đổi giá trị trong view:")
print(arr_2d)

Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
