In [1]:
import numpy as np
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
             [7,8]])
c = np.vstack((a,b))# Kết hợp theo chiều đầu tiên (trục dọc/trục 0)của mảng
d = np.hstack((a,b))# kết hợp theo trục ngang/trục 1
print(c)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
