In [1]:
import numpy as np
x =np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y]) # Kết hợp ma trận x,y

array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
             [7,8]])
#Kết hợp theo chiều đầu tiên(trục dọc/trục 0) của mảng
c = np.concatenate((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
# kết hợp theo chiều thứ 2( trục ngang/trục 1) của mảng, trục dc đánh chỉ số từ 0
d = np.concatenate([a,b], axis=1)
print(d)

[[1 2 5 6]
 [3 4 7 8]]
