In [1]:
import numpy as np
# Xóa 1 phần tử ở vị trí trong mảng
arr = np.array([3,1,4,2,5])
idx_to_delete = 2 # xóa phần tử 4 ở chỉ mục 2
new_arr =np.delete(arr,idx_to_delete)
new_arr

array([3, 1, 2, 5])

In [3]:
# Xóa nhiều phần tử trong mảng
arr = np.array([3,1,4,2,5])
idx_to_delete = [1,3]
new_arr = np.delete(arr,idx_to_delete)
new_arr

array([3, 4, 5])

In [5]:
# xóa phần tử trên mảng 2 chiều
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d,row_idx_to_delete,axis=0)
new_arr_2d

array([[1, 2, 3],
       [7, 8, 9]])