In [1]:
import numpy as np
arr =np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
sub_arr =arr[:2,:2]# slicing mảng con lấy 2 dòng 2 cột của mảng arr
print(sub_arr)

[[1 2]
 [4 5]]


In [3]:
sub_arr[0,0]= 10 # Chỉnh sửa phần tử ở dòng 0 cot 0 thành 10
print(sub_arr)

[[10  2]
 [ 4  5]]


In [4]:
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
