In [1]:
import numpy as np
arr =np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
sub_arr_copy = arr[:2,:2].copy()   # theem phương thức copy
print(sub_arr_copy)

[[1 2]
 [4 5]]


In [3]:
sub_arr_copy[0,0] = 10
print(sub_arr_copy)

[[10  2]
 [ 4  5]]


In [4]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
